### PR TITLE
added delete comment function

### PR DESCRIPTION
**Pull request by MolchanovaA**
When user deletes comment, 'deleted' note appears on it's comment. 
but if he would like to add new comment strait after deleting, without updating page, 'deleted' note appears on new comment as well. I haven't found resolution how to remove that notification from the new comment. Only updating page helps to see really deleted/added comments.

### CODE REVIEW

**Review by nc-modou — COMMENTED** [review]
Hey Alina, good job with the delete comment functionality so far!

To make this a better user experience AND to get rid of the 'deleting...' issue on a a new comment, let's make a deleted comment disappear entirely by removing it from the comments when a user deletes it. That will make it nicer to use as well because the user will see the comment disappear.

(When doing this, you don't have to fetch the comments again - just removing it from the state locally with a filter will be fine! Imagine if you had multiple users making comments, another GET request would bring in a lot of new comments which would be a bad user experience)

**Comment by MolchanovaA** [comment]
now deleted comment just hidding. but It's not reloalig list of comments until user update page manualy. I mean that if you add 00, then 11, then 22, then delete 22, and add 33 -> 33 will not appear! but deted 22 will. I have no idea how to fix it.

**Comment by MolchanovaA** [comment]
seems that I have fised it)) just double check before resubmittimg

**Review by ghost — APPROVED** [review]
Nice job, well done on the fix!

**Pull request merged**
